model = "gpt-5-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[projects."/Users/yuichi.sugio/Documents/VSCode/freeism-contribution-calculate"]
trust_level = "trusted"

[projects."/Users/yuichi.sugio/Documents/VSCode/dotfiles"]
trust_level = "trusted"

[projects."/Users/yuichi.sugio"]
trust_level = "trusted"

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]
